-- Paso 1: Ampliar el ENUM con valores nuevos y viejos juntos
ALTER TABLE `tickets` MODIFY COLUMN `subcategoria` ENUM(
  'SISTEMAS','SOPORTE_TECNICO','IMPRESORAS','REDES_INTERNET','CONFIGURACION_CORREO_OUTLOOK',
  'SISTEMAS_INSTITUCIONALES','EQUIPOS_DISPOSITIVOS','RED_INTERNET','CUENTAS_DOMINIO','CORREO_OUTLOOK',
  'SANITARIOS','ILUMINACION','MOVILIDAD',
  'SALA_JUNTAS','EQUIPO_AUDIOVISUAL','PRESTAMO_EQUIPO','MOBILIARIO','PAPELERIA'
) NOT NULL;

-- Paso 2: Migrar valores antiguos de TECNOLOGIAS a los nuevos
UPDATE `tickets` SET `subcategoria` = 'SISTEMAS_INSTITUCIONALES' WHERE `subcategoria` = 'SISTEMAS';
UPDATE `tickets` SET `subcategoria` = 'EQUIPOS_DISPOSITIVOS'     WHERE `subcategoria` IN ('SOPORTE_TECNICO', 'IMPRESORAS');
UPDATE `tickets` SET `subcategoria` = 'RED_INTERNET'             WHERE `subcategoria` = 'REDES_INTERNET';
UPDATE `tickets` SET `subcategoria` = 'CORREO_OUTLOOK'           WHERE `subcategoria` = 'CONFIGURACION_CORREO_OUTLOOK';

-- Paso 3: Dejar solo los valores nuevos en el ENUM
ALTER TABLE `tickets` MODIFY COLUMN `subcategoria` ENUM(
  'SISTEMAS_INSTITUCIONALES','EQUIPOS_DISPOSITIVOS','RED_INTERNET','CUENTAS_DOMINIO','CORREO_OUTLOOK',
  'SANITARIOS','ILUMINACION','MOVILIDAD',
  'SALA_JUNTAS','EQUIPO_AUDIOVISUAL','PRESTAMO_EQUIPO','MOBILIARIO','PAPELERIA'
) NOT NULL;
