// Script temporal para analizar departamentos no mapeados
const data = [];
process.stdin.on('data', d => data.push(d));
process.stdin.on('end', () => {
  const arr = JSON.parse(data.join(''));
  const validos = arr.filter(e => e.RFC && e.RFC.length === 13 && e.status === 1);

  const externoPrefijos = [
    'CIAC', 'CENTRO INTEGRAL DE ATENCI', 'MODULO DE ATENCI', 'MÓDULO DE ATENCI',
    'UNIDAD ADMINISTRATIVA DEL INSTITUTO CATASTRAL',
    'UNIDAD ADMINISTRATIVA DEL I.C.E.O',
    'DIRECCIÓN GENERAL DEL INSTITUTO CATASTRAL',
    'UNIDAD DE DELEGACIONES CATASTRALES',
  ];

  const yaAsignados = [
    'DIRECCIÓN ADMINISTRATIVA','DIRECCION ADMINISTRATIVA','DIRECCIóN ADMINISTRATIVA',
    'DIRECCIÓN ADMINISTRATIVA. FISCALIA','UNIDAD ADMINISTRATIVA (ARCHIVO)',
    'TESORERÍA','TESORERIA','SUBSECRETARÍA DE INGRESOS','DIRECCIÓN DE INGRESOS Y RECAUDACIÓN',
    'DEPARTAMENTO DE CONTROL DE INGRESOS','COORDINACIÓN TÉCNICA DE INGRESOS',
    'DEPARTAMENTO DE REGISTRO DE CONTRIBUYENTES','DEPTO. DE CTRL.DE MOV.AL PADRON DE MPIOS',
    'COORDINACIÓN DE CENTROS INTEGRALES DE ATENCIÓN AL CONTRIBUYENTE',
    'COORDINACION DE CENTROS INTEGRALES DE ATENCION AL CONTRIBUYENTE',
    'CENTRO INTEGRAL DE ASESORÍA Y ATENCIÓN','DEPARTAMENTO DE TRAMITACIÓN DE SOLICITUDES',
    'MODULO DE ATENCIÓN AL CONTRIBUYENTE DE OAXACA DE JUAREZ',
    'MóDULO DE ATENCIóN AL CONTRIBUYENTE DE OAXACA DE JUáREZ',
    'DEPARTAMENTO DE ENLACE Y COMUNICACIÓN','DEPARTAMENTO DE ENLACE Y VERIFICACIÓN',
    'OFICINA DEL SECRETARIO','SECRETARIO DE FINANZAS','ASESORÍA',
    'COORDINACIÓN DE GIRAS Y PROTOCOLO','DEPARTAMENTO DE PLANEACIÓN DE GIRAS',
    'DEPARTAMENTO DE PROTOCOLO Y LOGÍSTICA',
    'PERSONAL ADSCRITO A LA SECRETARÍA DE FINANZAS (HANGAR)',
    'CASA OFICIAL DE GOBIERNO','SUBSECRETARÍA DE PLANEACIÓN E INVERSIÓN PÚBLICA',
    'DIRECCIÓN DE PLANEACIÓN ESTATAL',
    'COORDINACIÓN DE APOYO TÉCNICO PARA LA PLANEACIÓN E INVERSIÓN',
    'COORDINACIÓN DE PLANEACIÓN Y PROYECTOS DE INVERSIÓN',
    'DIRECCIÓN DE PROGRAMACIÓN DE LA INVERSIÓN PÚBLICA',
    'DEPARTAMENTO DE ASUNTOS JURÍDICOS','DIRECCIÓN DE NORMATIVIDAD Y ASUNTOS JURÍDICOS',
    'PROCURADURÍA FISCAL','UNIDAD JURÍDICA','DIRECCIÓN DE LO CONTENCIOSO',
    'DEPARTAMENTO DE JUICIOS Y RECURSOS','DEPARTAMENTO DE PROCEDIMIENTOS ADMINISTRATIVOS',
    'DEPARTAMENTO DE NORMATIVIDAD','DEPARTAMENTO DE NORMATIVIDAD Y DESARROLLO METODOLÓGICO',
    'SUBSECRETARÍA DE EGRESOS, CONTABILIDAD Y TESORERÍA','UNIDAD TÉCNICA',
    'UNIDAD DE INFORMES SOBRE EL ESTADO DE LA GESTIÓN PÚBLICA',
    'CENTRO DE IMPLEMENTACIÓN,EVALUACIÓN Y SEGUIMIENTO DEL P.M.A.C',
    'OTORGAMIENTO DE SERVICIOS ADMINISTRATIVOS(DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN)',
    'DEPARTAMENTO DE ADMINISTRACIÓN TRIBUTARIA','DEPARTAMENTO DE ADMINISTRACIóN TRIBUTARIA',
    'DEPARTAMENTO DE ADMINISTRACION TRIBUTARIA','DEPARTAMENTO DE REGISTRO Y CONTROL DE CRÉDITOS',
    'COORDINACIÓN DE COBRO COACTIVO','COORDINACIóN DE COBRO COACTIVO',
    'COORDINACIÓN DE VISITAS DOMICILIARIAS','COORDINACIÓN DE REVISIÓN DE GABINETE Y MASIVA',
    'COORDINACIóN DE REVISIÓN DE GABINETE Y MASIVA','COORDINACIóN DE REVISIóN DE GABINETE Y MASIVA',
    'DEPARTAMENTO DE REVISIÓN DE GABINETE','DEPARTAMENTO DE VERIFICACIÓN Y REVISIÓN DE MASIVAS',
    'DEPARTAMENTO DE VERIFICACIóN Y REVISIóN DE MASIVAS','DEPARTAMENTO DE CONTROL DE OBLIGACIONES',
    'DEPARTAMENTO DE REVISIÓN DE DICTÁMENES','DEPARTAMENTO DE REVISIóN DE DICTáMENES',
    'DEPARTAMENTO DE CONSULTAS, SOLICITUDES Y NOTIFICACIONES',
    'DEPARTAMENTO DE CONSULTAS SOLICITUDES Y NOTIFICACIONES',
    'DEPARTAMENTO DE REVISIÓN A RENGLONES ESPECÍFICOS',
    'DEPARTAMENTO DE REVISIóN A RENGLONES ESPECíFICOS',
    'DEPARTAMENTO DE AUDITORÍAS A PERSONAS FÍSICAS',
    'DEPARTAMENTO DE AUDITORÍAS A PERSONAS MORALES',
    'DEPARTAMENTO DE CONTROL Y EJECUCIÓN DE CRÉDITOS','DEPARTAMENTO DE SEGUIMIENTO DE CRÉDITOS',
    'DIRECCIÓN DE AUDITORÍA E INSPECCIÓN FISCAL',
    'COORDINACIÓN DE AUDITORÍAS, ARMONIZACIÓN CONTABLE Y FINANCIERA',
    'DEPARTAMENTO DE REVISIÓN Y ANÁLISIS DEL SECTOR CENTRAL',
    'DEPARTAMENTO DE REVISIÓN Y ANÁLISIS DEL SECTOR PARAESTATAL',
    'DEPARTAMENTO DE ANÁLISIS Y ARMONIZACIÓN CONTABLE',
    'DEPARTAMENTO DE REVISIÓN Y ANÁLISIS CONTABLE DE LOS INGRESOS',
    'DEPARTAMENTO DE ATENCIÓN Y SEGUIMIENTO A LOS PROCESOS DE AUDITORÍAS',
    'DEPARTAMENTO DE REVISIÓN FINANCIERA','DIRECCIÓN DE CONTABILIDAD GUBERNAMENTAL',
    'DEPARTAMENTO DE RECURSOS FINANCIEROS','DEPARTAMENTO DE DEUDA PÚBLICA',
    'DEPARTAMENTO DE FIDEICOMISOS PÚBLICOS','DIRECCIÓN DE PRESUPUESTO','DIRECCION DE PRESUPUESTO',
    'COORDINACIÓN DE GESTIÓN PRESUPUESTARIA','COORDINACIÓN DE CONTROL FINANCIERO',
    'COORDINACIÓN DE PROCESAMIENTO DE CUENTAS POR LIQUIDAR CERTIFICADAS Y SEGUIMIENTO PRESUPUESTARIO A GASTO DE OPERACIÓN',
    'COORDINACIÓN DE MONITOREO DEL GASTO','DEPARTAMENTO DE SEGUIMIENTO PRESUPUESTARIO A GASTO DE OPERACIÓN',
    'DEPARTAMENTO DE GESTIÓN PRESUPUESTARIA "A"','DEPARTAMENTO DE GESTIÓN PRESUPUESTARIA "B"',
    'DEPARTAMENTO DE PRESUPUESTO "A"','DEPARTAMENTO DE PRESUPUESTO "B"',
    'DEPARTAMENTO DE POLÍTICA PRESUPUESTARIA','DEPARTAMENTO DE PLANEACIÓN Y EVALUACIÓN FINANCIERA',
    'DEPARTAMENTO DE PROGRAMACIÓN DE MINISTRACIONES Y PAGOS',
    'DEPARTAMENTO DE PROGRAMACIÓN FEDERAL Y ESTATAL','DEPARTAMENTO DE PROGRAMACIóN FEDERAL Y ESTATAL',
    'DEPARTAMENTO DE PROGRAMAS FEDERALES','DEPARTAMENTO DE PROCESAMIENTO Y ANÁLISIS DE LA INFORMACIÓN',
    'DEPARTAMENTO DE RECURSOS HUMANOS','DEPARTAMENTO DE CAPACITACIÓN Y ASISTENCIA TÉCNICA',
    'DEPARTAMENTO DE SEGUIMIENTO ADMINISTRATIVO','DEPARTAMENTO DE SERVICIOS GENERALES',
    'DEPARTAMENTO DE RECURSOS MATERIALES','DEPARTAMENTO DE GESTIÓN Y CONTROL DE FORMAS OFICIALES VALORADAS',
    'DEPARTAMENTO DE CONTROL DE FONDOS',
  ];

  const asignadosSet = new Set(yaAsignados);

  const deptCount = {};
  validos.forEach(e => {
    const d = (e.DEPARTAMENTO || 'SIN_DEPT').trim();
    if (asignadosSet.has(d)) return;
    const esExterno = externoPrefijos.some(p => d.toUpperCase().startsWith(p.toUpperCase()));
    if (!deptCount[d]) deptCount[d] = { count: 0, externo: esExterno };
    deptCount[d].count++;
  });

  const internos = Object.entries(deptCount).filter(([,v]) => !v.externo).sort((a,b) => b[1].count - a[1].count);
  const externos = Object.entries(deptCount).filter(([,v]) => v.externo).sort((a,b) => b[1].count - a[1].count);

  console.log('=== INTERNOS sin mapear → Nivel 3 ===');
  internos.forEach(([d,v]) => console.log(`  ${v.count}\t${d}`));
  console.log(`\nTotal internos N3: ${internos.reduce((s,[,v])=>s+v.count,0)}`);
  console.log('\n=== EXTERNOS (fuera del edificio) ===');
  externos.forEach(([d,v]) => console.log(`  ${v.count}\t${d}`));
  console.log(`\nTotal externos: ${externos.reduce((s,[,v])=>s+v.count,0)}`);
});
