-- AlterTable
ALTER TABLE `catalogo_recursos` ALTER COLUMN `updatedAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `unidades_recurso` ALTER COLUMN `updatedAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `usuarios` MODIFY `rol` ENUM('ADMIN', 'TECNICO_TI', 'TECNICO_REDES', 'TECNICO_SERVICIOS', 'MESA_AYUDA', 'GESTOR_RECURSOS_MATERIALES', 'EMPLEADO', 'RESPONSABLE_TI', 'RESPONSABLE_REDES', 'RESPONSABLE_MANTENIMIENTO', 'RESPONSABLE_RECURSOS_MATERIALES', 'TECNICO_ELECTRICISTA', 'TECNICO_PLOMERO', 'TECNICO_MOVILIDAD', 'GESTOR_SALAS_JUNTA', 'GESTOR_RECURSOS', 'GESTOR_INVENTARIO') NOT NULL;
