-- Paso 1: ampliar el ENUM añadiendo nuevos valores junto a los viejos
ALTER TABLE `tickets` MODIFY COLUMN `subcategoria` ENUM(
  'SISTEMAS','SOPORTE_TECNICO','IMPRESORAS','REDES_INTERNET','CONFIGURACION_CORREO_OUTLOOK',
  'SANITARIOS','ILUMINACION','MOVILIDAD',
  'SALA_JUNTAS','EQUIPO_AUDIOVISUAL','PRESTAMO_EQUIPO','MOBILIARIO','PAPELERIA',
  'SISTEMAS_INSTITUCIONALES','EQUIPOS_DISPOSITIVOS','RED_INTERNET','CUENTAS_DOMINIO','CORREO_OUTLOOK'
) NOT NULL;

-- Paso 2: migrar valores viejos → nuevos (tabla vacía, por si acaso)
UPDATE `tickets` SET `subcategoria` = 'SISTEMAS_INSTITUCIONALES'   WHERE `subcategoria` = 'SISTEMAS';
UPDATE `tickets` SET `subcategoria` = 'EQUIPOS_DISPOSITIVOS'        WHERE `subcategoria` IN ('SOPORTE_TECNICO','IMPRESORAS');
UPDATE `tickets` SET `subcategoria` = 'RED_INTERNET'                WHERE `subcategoria` = 'REDES_INTERNET';
UPDATE `tickets` SET `subcategoria` = 'CORREO_OUTLOOK'              WHERE `subcategoria` = 'CONFIGURACION_CORREO_OUTLOOK';

-- Paso 3: dejar solo los valores actuales del schema
ALTER TABLE `tickets` MODIFY COLUMN `subcategoria` ENUM(
  'SISTEMAS_INSTITUCIONALES','EQUIPOS_DISPOSITIVOS','RED_INTERNET','CUENTAS_DOMINIO','CORREO_OUTLOOK',
  'SANITARIOS','ILUMINACION','MOVILIDAD',
  'SALA_JUNTAS','EQUIPO_AUDIOVISUAL','PRESTAMO_EQUIPO','MOBILIARIO','PAPELERIA'
) NOT NULL;

-- También corregir procesos_definicion si tiene la misma columna
ALTER TABLE `procesos_definicion` MODIFY COLUMN `subcategoria` ENUM(
  'SISTEMAS_INSTITUCIONALES','EQUIPOS_DISPOSITIVOS','RED_INTERNET','CUENTAS_DOMINIO','CORREO_OUTLOOK',
  'SANITARIOS','ILUMINACION','MOVILIDAD',
  'SALA_JUNTAS','EQUIPO_AUDIOVISUAL','PRESTAMO_EQUIPO','MOBILIARIO','PAPELERIA'
) NOT NULL;
